"""
Deliverer v2 — GitHub PR 自动交付 + 状态跟踪

v2 变更:
  - deliver() 接收结构化 changes: list[dict] (从 solver 的 FileChange)
  - 按 path 覆写目标文件, 而非创建新 .patch 文件
  - 跑 changes 中指定的 test_command
  - 分支名加时间戳防冲突
  - apply_changes() 独立方法, 方便复用
"""

import hashlib
import json
import os
import subprocess
import tempfile
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path
from typing import Optional


@dataclass
class DeliveryResult:
    success: bool
    pr_url: str = ""
    branch: str = ""
    error: str = ""


@dataclass
class PRStatus:
    pr_url: str
    state: str = "open"          # open / merged / closed / changes_requested
    mergeable: bool = False
    check_status: str = ""       # success / failure / pending
    last_checked: str = ""
    auto_fix_attempts: int = 0
    bounty_claimed: bool = False


def _extract_issue_number(url: str) -> int:
    import re
    m = re.search(r'/issues?/(\d+)', url)
    return int(m.group(1)) if m else 0


class PRDeliverer:
    """自动 fork → branch → commit → push → PR (v2: 结构化变更)"""

    def __init__(self, github_token: str = ""):
        self.token = github_token or os.environ.get("GITHUB_TOKEN", "")

    def deliver(self, repo: str, issue_url: str,
                changes: list[dict],   # ← 结构化: [{"path": "...", "action": "...", "content": "..."}]
                title: str, description: str = "",
                dry_run: bool = False) -> DeliveryResult:
        """自动提 PR

        Args:
            repo: owner/repo (如 "guyu-adam/forager")
            issue_url: issue 链接
            changes: solver 输出的结构化文件变更
            title: PR 标题
            description: PR 描述
            dry_run: True=只看不做 (不 fork 不提 PR)
        """
        result = DeliveryResult(success=False)

        if not self.token:
            result.error = "GITHUB_TOKEN not set"
            return result

        issue_number = _extract_issue_number(issue_url)
        if not issue_number:
            result.error = f"Cannot extract issue number from {issue_url}"
            return result

        timestamp = datetime.now().strftime("%m%d-%H%M")
        branch_name = f"forager/fix-{issue_number}-{timestamp}"

        if dry_run:
            result.success = True
            result.branch = branch_name
            result.pr_url = f"(dry-run) would create PR for {repo}#{issue_number}"
            return result

        with tempfile.TemporaryDirectory() as tmpdir:
            try:
                # 1. Clone
                subprocess.run(
                    ["gh", "repo", "clone", repo, tmpdir],
                    capture_output=True, check=True, timeout=60,
                    env={**os.environ, "GITHUB_TOKEN": self.token}
                )

                # 2. Create branch
                subprocess.run(
                    ["git", "-C", tmpdir, "checkout", "-b", branch_name],
                    capture_output=True, check=True
                )

                # 3. Apply changes — 按文件路径覆写
                self._apply_changes(tmpdir, changes)

                # 4. Run tests (if changes specify test_command)
                test_commands = [c.get("test_command", "") for c in changes if c.get("test_command")]
                if test_commands:
                    test_cmd = test_commands[0]
                    test_result = subprocess.run(
                        test_cmd.split(), cwd=tmpdir,
                        capture_output=True, text=True, timeout=120
                    )
                    if test_result.returncode != 0:
                        result.error = f"Tests failed, PR aborted: {test_result.stderr[:300]}"
                        return result

                # 5. Commit
                subprocess.run(
                    ["git", "-C", tmpdir, "add", "-A"],
                    capture_output=True, check=True
                )
                commit_msg = (
                    f"fix: {title}\n\n"
                    f"Closes #{issue_number}\n\n"
                    f"{description}\n\n"
                    f"🤖 Auto-generated by Forager"
                )
                subprocess.run(
                    ["git", "-C", tmpdir, "commit", "-m", commit_msg],
                    capture_output=True, check=True
                )

                # 6. Push
                subprocess.run(
                    ["git", "-C", tmpdir, "push", "origin", branch_name],
                    capture_output=True, check=True, timeout=30,
                    env={**os.environ, "GITHUB_TOKEN": self.token}
                )

                # 7. Create PR
                pr_result = subprocess.run(
                    ["gh", "pr", "create",
                     "--repo", repo,
                     "--head", branch_name,
                     "--base", "main",
                     "--title", f"fix: {title[:60]}",
                     "--body", (
                         f"Closes #{issue_number}\n\n"
                         f"{description}\n\n"
                         f"🤖 Auto-generated by [Forager](https://github.com/guyu-adam/forager)"
                     ),
                     "--json", "url"],
                    capture_output=True, text=True, timeout=30,
                    env={**os.environ, "GITHUB_TOKEN": self.token}
                )

                if pr_result.returncode == 0:
                    pr_data = json.loads(pr_result.stdout)
                    result.success = True
                    result.pr_url = pr_data.get("url", "")
                    result.branch = branch_name
                else:
                    result.error = pr_result.stderr

            except subprocess.CalledProcessError as e:
                result.error = f"Command failed: {e.stderr if hasattr(e, 'stderr') else e}"
            except Exception as e:
                result.error = str(e)

        return result

    def _apply_changes(self, repo_dir: str, changes: list[dict]):
        """在目标 repo 目录中应用文件变更"""
        for change in changes:
            path = change.get("path", "")
            action = change.get("action", "modify")
            content = change.get("content", "")

            if not path or not content:
                continue

            filepath = Path(repo_dir) / path

            if action in ("modify", "create"):
                filepath.parent.mkdir(parents=True, exist_ok=True)
                filepath.write_text(content, encoding="utf-8")
            elif action == "delete":
                if filepath.exists():
                    filepath.unlink()


class PRTracker:
    """PR 状态跟踪"""

    def check(self, pr_url: str) -> PRStatus:
        """检查 PR 状态"""
        status = PRStatus(pr_url=pr_url, last_checked=datetime.now().isoformat())

        try:
            r = subprocess.run(
                ["gh", "pr", "view", pr_url, "--json",
                 "state,mergeable,statusCheckRollup"],
                capture_output=True, text=True, timeout=15
            )
            if r.returncode == 0:
                data = json.loads(r.stdout)
                status.state = data.get("state", "OPEN").lower()
                status.mergeable = data.get("mergeable", False) or False

                checks = data.get("statusCheckRollup", []) or []
                status.check_status = "success" if all(
                    c.get("status") == "SUCCESS" for c in checks
                ) else ("failure" if any(
                    c.get("status") == "FAILURE" for c in checks
                ) else "pending")
        except Exception:
            pass

        return status

    def is_mergeable(self, pr_url: str) -> bool:
        """检查是否可合并"""
        s = self.check(pr_url)
        return s.state == "open" and s.check_status == "success"
